development:
  adapter: postgresql
  encoding: unicode
  database: shipstation_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: shipstation_test
  pool: 5
  username: postgres
  password: postgres